notifications:
  email: false
language: node_js
node_js:
  - '8.9.0'
before_install:
- pip install --user codecov
before_script:
  - "npm install"
script:
  - npm run travis
branches:
  except:
    - /.*\/.*/
